package truenasstore

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/SemperSupra/garm-provider-truenas/internal/provider"
)

type g2Fixture struct {
	AppName string         `json:"app_name"`
	State   string         `json:"state"`
	Compose map[string]any `json:"compose"`
}

type g2Bundle struct {
	Schema                string               `json:"schema"`
	ProviderProductSource string               `json:"provider_product_source"`
	ProducerSource        string               `json:"producer_source"`
	ControllerID          string               `json:"controller_id"`
	PoolID                string               `json:"pool_id"`
	Runner                map[string]any       `json:"runner"`
	Fixtures              map[string]g2Fixture `json:"fixtures"`
	Claims                []string             `json:"claims"`
	NonClaims             []string             `json:"non_claims"`
}

func composeObjectForG2(t *testing.T, spec provider.AppSpec) map[string]any {
	t.Helper()
	raw, err := composeConfig(spec)
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal([]byte(raw), &doc); err != nil {
		t.Fatal(err)
	}
	return doc
}

func TestExportNestedG2FixtureBundle(t *testing.T) {
	out := os.Getenv("G2_FIXTURE_OUT")
	if out == "" {
		t.Skip("G2_FIXTURE_OUT not set")
	}

	local := fixedSpec()
	local.Name = "garm-g2controller-runner-1"
	local.ControllerID = "g2-controller"
	local.PoolID = "g2-pool"
	local.CallbackURL = "https://garm-g2.invalid/api/v1/callbacks"
	local.MetadataURL = "https://garm-g2.invalid/api/v1/metadata"
	local.BootstrapToken = "g2-public-fixture-token"

	foreign := local
	foreign.Name = "garm-othercontroller-runner-2"
	foreign.ControllerID = "other-controller"

	localDoc := composeObjectForG2(t, local)
	foreignDoc := composeObjectForG2(t, foreign)

	driftDoc := composeObjectForG2(t, local)
	driftDoc["services"].(map[string]any)["runner"].(map[string]any)["restart"] = "always"

	producerSource := os.Getenv("G2_PRODUCER_SOURCE")
	if producerSource == "" {
		producerSource = "unknown"
	}

	bundle := g2Bundle{
		Schema:                "semper-supra.garm-provider-truenas-g2-fixtures/1",
		ProviderProductSource: "14535745dc3aa3c0b5466da7c704bca4d23dcec5",
		ProducerSource:        producerSource,
		ControllerID:          local.ControllerID,
		PoolID:                local.PoolID,
		Runner: map[string]any{
			"image":             provider.RunnerImage,
			"version":           provider.RunnerVersion,
			"tool_url":          provider.RunnerToolURL,
			"tool_filename":     provider.RunnerToolFilename,
			"tool_sha256":       provider.RunnerToolSHA256,
			"cpu":               provider.GeneralCPU,
			"memory_bytes":      provider.GeneralMemoryBytes,
			"execution_profile": provider.FlavorLinuxGeneral,
		},
		Fixtures: map[string]g2Fixture{
			"valid_local": {
				AppName: local.Name,
				State:   "STOPPED",
				Compose: localDoc,
			},
			"valid_foreign": {
				AppName: foreign.Name,
				State:   "STOPPED",
				Compose: foreignDoc,
			},
			"managed_drift": {
				AppName: "garm-g2controller-drift-1",
				State:   "STOPPED",
				Compose: driftDoc,
			},
		},
		Claims: []string{
			"valid fixtures are generated by exact provider composeConfig",
			"foreign fixture differs only by provider ownership identity",
			"managed drift fixture changes one realized-profile field after exact generation",
		},
		NonClaims: []string{
			"no TrueNAS runtime realization",
			"no GitHub JIT registration",
			"no runner bootstrap success",
			"no physical-host qualification",
		},
	}

	// Keep the drift fixture name aligned with its local ownership label. Name
	// shape is only a discovery prefilter; ownership remains label-based.
	driftRunner := bundle.Fixtures["managed_drift"].Compose["services"].(map[string]any)["runner"].(map[string]any)
	labels := driftRunner["labels"].(map[string]any)
	labels[labelController] = local.ControllerID
	labels[labelPool] = local.PoolID

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		t.Fatal(err)
	}
	raw, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, '\n')
	if err := os.WriteFile(out, raw, 0o644); err != nil {
		t.Fatal(err)
	}
}
